import React from "react";
import { Link } from "react-router-dom";

export const About: React.FC = () => <div className="site-page">
  <section className="page-hero about-hero"><div className="page-hero-grid"></div><div><span className="eyebrow"><span></span> ABOUT YESITECH</span><h1>Technology with<br/><em>purpose and precision.</em></h1><p>We are a software engineering company for organizations that refuse to stand still—curious people solving meaningful problems with thoughtful technology.</p></div><div className="about-monogram"><b>Y</b><span>THINK<br/>BUILD<br/>EVOLVE</span></div></section>
  <section className="section story-section"><div className="section-heading"><span className="kicker">OUR POINT OF VIEW</span><h2>Good technology fades into the background.<br/><em>Great outcomes don’t.</em></h2></div><div className="story-grid"><p className="story-lead">Yesitech exists to make advanced technology genuinely useful—clear to understand, practical to operate and powerful enough to create lasting advantage.</p><div><p>We partner with teams at moments of change: launching new products, modernizing critical systems, making sense of complex data or adopting AI responsibly.</p><p>Our approach combines product thinking with strong engineering discipline. That means asking the hard questions early, building only what matters and leaving every system better than we found it.</p></div></div></section>
  <section className="values-section"><div className="section-heading"><span className="kicker kicker-mint">HOW WE SHOW UP</span><h2>Principles over<br/><em>promises.</em></h2></div><div className="values-grid"><article><span>01</span><h3>Be relentlessly useful</h3><p>Technology is only impressive when it improves a real outcome.</p></article><article><span>02</span><h3>Make complexity clear</h3><p>We communicate plainly and bring structure to uncertain problems.</p></article><article><span>03</span><h3>Own the outcome</h3><p>We act like partners, stay accountable and finish what we start.</p></article><article><span>04</span><h3>Build to endure</h3><p>Quality, security and maintainability are decisions made from day one.</p></article></div></section>
  <section className="stat-band"><div><strong>Full-stack</strong><span>Product ownership</span></div><div><strong>Cloud-first</strong><span>Modern architecture</span></div><div><strong>AI-ready</strong><span>Responsible innovation</span></div><div><strong>Human-led</strong><span>True collaboration</span></div></section>
  <section className="cta-section"><span className="kicker">BUILD WITH US</span><h2>Smart people.<br/><em>Shared ambition.</em></h2><p>Bring us your hardest technology problem. We’ll bring curiosity, clarity and the craft to solve it.</p><Link to="/contact" className="button button-dark">Meet the team <span>↗</span></Link></section>
</div>;
