import React from "react";
import { Link } from "react-router-dom";

const capabilities = [
  { n: "01", title: "AI that works", text: "Production-ready AI agents, RAG, semantic search and intelligent automation built around your real workflows.", tag: "Generative AI" },
  { n: "02", title: "Software that scales", text: "Reliable full-stack platforms, APIs and microservices engineered for performance, security and growth.", tag: "Product engineering" },
  { n: "03", title: "Data that delivers", text: "Modern ETL pipelines, cloud migrations and analytics that turn fragmented information into clear decisions.", tag: "Data & cloud" },
];
const stack = ["Agentic AI","MCP Server", "AI Agents", ".NET Core", "Python", "React/Angular", "AWS/Azure", "Kubernetes"];

export const Home: React.FC = () => <div className="site-page">
  <section className="hero"><div className="hero-glow glow-one"></div><div className="hero-glow glow-two"></div>
    <div className="hero-content"><div className="eyebrow"><span></span> Software, cloud & AI engineering</div><h1>Build what’s next.<br/><em>Intelligently.</em></h1><p>We design intelligent digital products that help ambitious companies automate operations, unlock their data and move at remarkable speed.</p><div className="hero-actions"><Link to="/contact" className="button button-primary">Start your project <span>↗</span></Link><Link to="/services" className="button button-ghost">Explore capabilities <span>→</span></Link></div><div className="hero-proof"><div><strong>10+</strong><span>Core disciplines</span></div><div><strong>24/7</strong><span>Technical support</span></div><div><strong>360°</strong><span>Delivery ownership</span></div></div></div>
    <div className="hero-visual" aria-hidden="true"><div className="orbit orbit-one"><i></i></div><div className="orbit orbit-two"><i></i></div><div className="visual-core"><span className="core-pulse"></span><b>Y</b><small>INTELLIGENCE<br/>ENGINE</small></div><div className="float-card card-ai"><span>✦</span><div><small>AI SYSTEMS</small><strong>Learning & evolving</strong></div></div><div className="float-card card-cloud"><span>⌁</span><div><small>CLOUD SCALE</small><strong>Always available</strong></div></div><div className="code-chip chip-one">&lt;/&gt;</div><div className="code-chip chip-two">01</div></div>
    <div className="scroll-cue"><span></span>SCROLL TO DISCOVER</div>
  </section>
  <section className="logo-strip"><span>TECHNOLOGIES WE BUILD WITH</span><div>{stack.map(x => <b key={x}>{x}</b>)}</div></section>
  <section className="section section-light"><div className="section-heading split-heading"><div><span className="kicker">WHAT WE DO</span><h2>Complex technology.<br/><em>Clear business impact.</em></h2></div><p>From an ambitious idea to dependable production systems, our engineers bring strategy, software, data and AI together under one roof.</p></div><div className="capability-grid">{capabilities.map(item => <article className="capability-card" key={item.n}><div className="card-top"><span>{item.n}</span><i>↗</i></div><div className="service-symbol">{item.n === "01" ? "✦" : item.n === "02" ? "⌘" : "⌁"}</div><small>{item.tag}</small><h3>{item.title}</h3><p>{item.text}</p><Link to="/services">Explore service <span>→</span></Link></article>)}</div></section>
  <section className="dark-feature"><div className="feature-copy"><span className="kicker kicker-mint">WHY YESITECH</span><h2>Your vision deserves more than just <em>working code.</em></h2><p>We think like product owners, engineer for the long term and communicate without the fog. Every engagement is grounded in measurable outcomes.</p><div className="feature-list"><span>Strategy before syntax</span><span>Senior engineering mindset</span><span>Security built in</span><span>Transparent delivery</span></div><Link to="/about" className="text-link">Meet your technology partner →</Link></div><div className="feature-panel"><div className="panel-label"><span>DELIVERY SYSTEM</span><b>● LIVE</b></div><div className="signal"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div className="metric"><strong>Ideas</strong><span></span><b>Impact</b></div><div className="panel-footer"><span>DISCOVER</span><span>DESIGN</span><span>ENGINEER</span><span>EVOLVE</span></div></div></section>
  <section className="cta-section"><span className="kicker">YOUR NEXT MOVE</span><h2>Have a bold idea?<br/><em>Let’s make it real.</em></h2><p>Tell us where you want to go. We’ll bring the technical clarity and engineering power to get you there.</p><Link to="/contact" className="button button-dark">Talk to our team <span>↗</span></Link></section>
</div>;
